spring.application.name=mock-payment-service
server.port=8085
mock.webhook.target-url=http://localhost:8080/api/v1/webhooks/payment
mock.webhook.delay-ms=2500
mock.scenario.timeout-delay-ms=30000
mock.scenario.slow-delay-ms=3000